### ISSUE TITLE
Threat from Vampiric Embrace ability/talent incorrectly applied/attributed

### ISSUE THREAD

**Issue by TheStealthDude** [dfherr/LibThreatClassic2#28] opened 2020-03-25 13:35 UTC
This is probably a niche issue, as it's likely not having an impact on the end-game raiding, but I am playing with a group that consists of 2 shamans (one of which is tanking) a Shadow Priest (with Vampiric embrace), and a a warlock.  The tank, priest, and warlock are all using a threat meter based on this threat library.  

We are finding that the shadow Priest threat is not aligning with when they pull aggro from the tank.  The priest will pull aggro in longer fights with much less threat caused than the tank.  We believe the threat caused by the healing from Vampiric Embrace (either from shadow damage caused by the Warlock, the priest, or both) is not being properly applied to the Priest.  We think this results in the Priest pulling aggro even when it appears they have much less threat caused than the tank.

This is something we have just noticed recently, so I dont have any saved logs yet.  I can start trying to save our logs as we continue to play and possibly run some tests if that might be helpful.  Just wanted to bring this to your attention if it was something that was unknown until now.

**Comment by dfherr** [comment] 2020-04-11 23:34
Did you maybe have silent resolve skilled as a shadow priest? Because silent resolve was incorrectly not considered for shadow spells. this is fixed now.

**Comment by dfherr** [comment] 2020-04-22 06:52
closing as missing additional information and likely caused by some of the other bugs that have been fixed by now.

**Closed as completed by dfherr** 2020-04-22 06:52 UTC
