### ISSUE TITLE
Does ThreatClassic-1.0(LibThreatClassic), and LibThreatClassic2 collide?

### ISSUE THREAD

**Issue by lorem-ipsum-dolor-sit** [dfherr/LibThreatClassic2#9] opened 2020-01-05 20:45 UTC
We have noticed that some player stays at top of the threat meter (Details/ThreatClassic2) after a knockback from Onyixa.

We are trying to reproduce the issue, so we can share data but at the current state, we think that both Lib's collide. Cause some use both (LibThreatClassic and LibThreatClassic2).

**Comment by dfherr** [comment] 2020-01-06 02:34
One libs ingame name is `ThreatClassic-1.0` and this ones is `LibThreatClassic2`. In regards to actual libs there is no `LibThreatClassic` (but the github project of `ThreatClassic-1.0` is named LibThreatClassic, to make things confusing). `ThreatClassic-1.0` and `LibThreatClassic2` are incompatible, but do not interfere with each other. Players using `ThreatClassic-1.0` will not show up in threameters of players with `LibThreatClassic2` and vice versa. They are seperate worlds. Players using `ThreatClassic-1.0` will not lose threat in their threatmeter, when hit by a knock back or a fireball. They should update their addons.

What do you mean "some players"? The threat reduce is only applied to players hit by Onyxia's `Knock Away` spell. So, if you got hit by `Knock Away` in your combat log, you should get threat reduced. This information is available in the out-of-game combatlog (turn on with `/combatlog`, remember to turn back off), if you can't find it ingame. It's also available in warcraftlogs.

As far as I know, the spell that knocks you (and possibly others) back is called `Wing Buffet` and at the same time `Knock Away` is only applied to Onyxia's main target (the tank). That means multiple people could get knocked back, but only the main target loses threat. However, I never tested if other targets that get knock backed are also hit by `Knock Away`.

I close this for now. Please reopen, if you have further information and think there is a bug.

**Closed as completed by dfherr** 2020-01-06 02:34 UTC

**Comment by lorem-ipsum-dolor-sit** [comment] 2020-01-06 09:41
Thanks for the response, and sorry for the bad description - but you understood me :D

Here is a [link to our combat log](https://classic.warcraftlogs.com/reports/9GMC6mpbWVQ7hxdt#fight=last&type=casts&view=events&hostility=1&start=186721&end=229460). I tried to get much as possible information, but just feel and reminding from two players they were in the situation.

The tank at timestamp `00:00:48.500` got `Knock Away`, told me the threat reduction was not visible in the in-game threat meter(using ClassicThreatMeter and ThreatClassic2) also the warlock at `00:00:56.152` told the same (using Details and ThreatClassic2). That the tank stays on top of threat meter, but Onyixa has the warlock as target.

When we look at `00:00:47.979` and `00:00:49.973` in  [Threat on warcraft logs](https://classic.warcraftlogs.com/reports/9GMC6mpbWVQ7hxdt#fight=last&type=threat&view=events&start=186721&end=229460) it sounds possible.

I have no video proof of how the threat meter looked in-game - that's just the reminding of two players.  Cause I'm not really into the threat calculation, so I summed up both player's raw damage(no threat multiplier on spells or something, from start to 1 minute) and reduced the tank threat by 75% that's what I saw in your code what happens when `Knock Away` hits.

https://github.com/dfherr/LibThreatClassic2/blob/1a71305804ca0748359294d130016c95c2ec95f9/NPCModules/Onyxia/Onyxia.lua#L21

The results are, the tanks threat is `35540` with `reducing of 75%` it is `26655`. And the warlocks threat is `20530`, so again it sounds possible that something went wrong.

But I have no idea what's wrong and now I need help.

**Comment by nano1895pearson** [comment] 2020-01-06 10:39
@stefan0uh 

https://classic.warcraftlogs.com/reports/9GMC6mpbWVQ7hxdt#fight=last&type=damage-done&start=162056&end=212897&pins=0%24Separate%24%23244F4B%24casts%24-1%240.0.0.Any%240.0.0.Any%24true%240.0.0.Any%24true%2419633

Warlock gained aggro after second knockaway roughly

From 0 - 48.5s Warlock threat was 393.5 * 48.5 = 19084.75

Warrior Threat till first knockaway = 
131dps * 18 + 2 * 250 (shield slam) + 2 * 145 (HS) + 2 * 350 (revenge) + 2 * 265 (SA) = 4378 * 1.495 (defiance/prot) = 6545 


Warrior Threat after knockaway = 6545* .75 = 4908


Warrior threat gained to second knockaway =
https://classic.warcraftlogs.com/reports/9GMC6mpbWVQ7hxdt#fight=last&type=damage-done&pins=0%24Separate%24%23244F4B%24casts%24-1%240.0.0.Any%240.0.0.Any%24true%240.0.0.Any%24true%2419633&source=36&start=179466&end=210111

216.1 * 31 + 3 * 250 + 6 * 145 + 3 * 355 + 7 * 265 = 11239.1 * 1.495 = 16802

Warr threat before 2nd knockaway = 4908 + 16802 = 21710

Warlock threat before 2nd knockaway = 394.6 * 48.5 = 19138.1

Warr threat after 2nd knockaway = 21710 * .75 = 16282.5

result is warlock gains aggro.

I have noticed sometimes that libthreatclassic sometimes doesnt sync / update for a while so maybe that was the problem.

**Comment by dfherr** [comment] 2020-01-06 11:41
> The tank at timestamp `00:00:48.500` got `Knock Away`, told me the threat reduction was not visible in the in-game threat meter(using ClassicThreatMeter and ThreatClassic2) also the warlock at `00:00:56.152` told the same (using Details and ThreatClassic2). That the tank stays on top of threat meter, but Onyixa has the warlock as target.

When tanking Onyxia, I actively lose 25% of my threat in Details, when getting knocked back. So I guess your tank looked at the wrong threat meter or he just looked on the order of players instead of the actual threat values. As @nano1895pearson pointed out he was still on top after the first knock away. 

Also the syncing is limited by chat throttle and sometimes delayed and unfortunately in rare cases dropped completely. There is nothing I know of I can do about that tho.

**Comment by lorem-ipsum-dolor-sit** [comment] 2020-01-06 14:37
alright, thanks for the dive in and explanation.

> he just looked on the order of players instead of the actual threat values

means the addon doesn't sort correctly? 

> Also the syncing is limited by chat throttle and sometimes delayed and unfortunately in rare cases dropped completely. There is nothing I know of I can do about that tho.

so it is not useful to have different threat meters or addons installed, that use the lib?

**Comment by mspk7305** [comment] 2020-01-06 14:43
Dbm uses ThreatLib, independent of Details. Why it does I don't know since it doesn't have a threat meter.

**Comment by dfherr** [comment] 2020-01-06 15:33
> > he just looked on the order of players instead of the actual threat values
> 
> means the addon doesn't sort correctly?

no it sorts correctly. That the boss is changing its target, doesn't mean the tank changed (otherthise the threatmeter would reorder everytime the boss casts a spell and such). So, if the new target doesn't have enough threat to change the tank, the addon doesn't change the tank. So your tank saw himself on top while the warlock had aggro, because based on the threat values (even with 25% deducted), the addon still thought he had the most threat. That's not a bug, but syncing delay.

I think this is a misconception, because the addon doesn't update instantly, but has delays. it especially has delays, if you are using `ThreatLib-1.0` and `LibThreatClassic2` at the same time, because it spams the chat and runs into throttle. That's why I closed the issue. I don't think this is a bug based on the information presented so far.

> > Also the syncing is limited by chat throttle and sometimes delayed and unfortunately in rare cases dropped completely. There is nothing I know of I can do about that tho.
> 
> so it is not useful to have different threat meters or addons installed, that use the lib?

It doesn't matter how many instances of `LibThreatClassic2` you have installed, only the latest version actively used. However, as I just said, using the old and new lib at the same time has chat capacity performance issues.

@mspk7305 
> Dbm uses ThreatLib, independent of Details. Why it does I don't know since it doesn't have a threat meter.

Newest DBM version removed `ThreatClassic-1.0` and comes with `LibThreatClassic2`. For a transition period it's still using `ThreatClassic-1.0` , if installed by another addon, but no longer loads it by itself. It uses that information to get the current active tank.
